### ISSUE TITLE
kernel errors and crashes on any significant (>10MB) enc/dec using mtk-eip93

### ISSUE THREAD

**Issue by rdslw** [vschagen/mtk-eip93#11]
Kernel: 5.4.63
distro: openwrt master patched with mtk-eip93

steps to reproduce:
1. have one partition (1GB enough) free to use
2. create cryptsetup luks container (use proper partition at the end!):
cryptsetup --cipher aes-xts-plain64      --key-size 256 --use-random --sector-size=4096 --type luks2 luksFormat /dev/sdc2
3. mount partition:
cryptsetup luksOpen /dev/sdc2 sdc2luks
4. try to read or write some more amount of data:
dd if=/dev/mapper/sdc2luks of=/dev/null bs=1M count=1000
5. observe errors:
[  339.973723] Buffer I/O error on dev dm-0, logical block 23433, async page read
[  339.991778] Buffer I/O error on dev dm-0, logical block 23437, async page read
[  340.336625] Buffer I/O error on dev dm-0, logical block 24001, async page read
[  475.223702] Buffer I/O error on dev dm-0, logical block 386, async page read
[  476.409915] Buffer I/O error on dev dm-0, logical block 972, async page read
[  476.424695] Buffer I/O error on dev dm-0, logical block 972, async page read

**Comment by vschagen** [comment]
EIP93 is not capable of aes-xts so it will not be used for this.

Trying to reproduce the error with "--ciper aes-cbc" does NOT create any error.

**Comment by rdslw** [comment]
@vschagen I was able quite reliable to generate this bug, AFAIK not only in XTS.
This was happening on the very same device and configuration (apart from kernel) which see no errors on big data writes while not using EIP93.

Would you like me to retest current version and provide you more data?

**Comment by rdslw** [comment]
I did retest, on newest version from repo (bb5fd1c88a8a74de06b70c281bceeb14d0d960ef) and kernel 5.4.85 and the problem is still present.

steps to reproduce needs slightly larger writing amount (10GB) to show it reliably, although once I saw the problem with read :-o

To reproduce bug I'm doing:
```
$ cryptsetup --cipher aes-xts-plain64  --key-size 256 --use-random --sector-size=4096 --type luks2 luksFormat /dev/md1
$ cryptsetup luksOpen /dev/md1 luks1test
$ dd if=/dev/zero bs=1024 count=10485760 of=/dev/mapper/luks1test
dd: error writing '/dev/mapper/luks1test': I/O error
715745+0 records in
715744+0 records out
$  dmesg |tail
[48705.736283] Buffer I/O error on dev dm-1, logical block 175924, lost async page write
[48705.736335] Buffer I/O error on dev dm-1, logical block 175925, lost async page write
[48705.736397] Buffer I/O error on dev dm-1, logical block 175926, lost async page write
[48705.736505] Buffer I/O error on dev dm-1, logical block 175927, lost async page write
[48705.736603] Buffer I/O error on dev dm-1, logical block 175928, lost async page write
[48705.736700] Buffer I/O error on dev dm-1, logical block 175929, lost async page write
[48705.738036] Buffer I/O error on dev dm-1, logical block 175930, lost async page write
[48705.738129] Buffer I/O error on dev dm-1, logical block 175931, lost async page write
[48705.738209] Buffer I/O error on dev dm-1, logical block 175932, lost async page write
[48705.738290] Buffer I/O error on dev dm-1, logical block 175933, lost async page write
```

I'm using md1 here as a device, however I tested it, and the error hits also if using single partition (e.g. sda1) as a base for cryptsetup device.

I'm willing to help with debugging more, just tell me what you need.

**Comment by vschagen** [comment]
Just a follow up on this one:

With the latest version I am not able to reproduce any of these errors.
