### ISSUE TITLE
Kernel crash when running tcrypt test

### ISSUE THREAD

**Issue by renhao0806** [vschagen/mtk-eip93#6]
There is a test module(tcrypt.c) in linux kernel crypto subsytem. I disable CONFIG_CRYPTO_MANAGER_DISABLE_TESTS to run tcrypt test when inserting module.

Kernel crash crash will be happened probably when running tcrypt test.

# insmod lib/modules/4.14.141/crypto-hw-eip93.ko

[   78.118387] mtk-eip93 1e004000.crypto: Assigning IRQ: 27
[   78.123792] Unhandled kernel unaligned access[#1]:
[   78.128566] CPU: 0 PID: 1381 Comm: insmod Not tainted 4.14.141 #0
[   78.134631] task: 8fe6ce00 task.stack: 8f340000
[   78.139136] $ 0   : 00000000 00000001 c9f7bd57 00ac6000
[   78.144347] $ 4   : 805f61fc 014080c0 81258600 ffffffff
[   78.149558] $ 8   : 00000522 000000cf 00000007 00000000
[   78.154767] $12   : 00000000 80600000 0001ce73 00000000
[   78.159975] $16   : 8fc02d00 014080c0 808d0000 c9f7bd57
[   78.165185] $20   : 8e538000 8fdbc810 8e538070 00000028
[   78.170395] $24   : 00000003 802d6ce0
[   78.175605] $28   : 8f340000 8f341b48 8e53eb48 80132b58
[   78.180816] Hi    : 00000124
[   78.183679] Lo    : 74e58000
[   78.186555] epc   : 80132c1c __kmalloc_track_caller+0x184/0x294
[   78.192446] ra    : 80132b58 __kmalloc_track_caller+0xc0/0x294
[   78.198245] Status: 11008403 KERNEL EXL IE
[   78.202416] Cause : 40800010 (ExcCode 04)
[   78.206402] BadVA : c9f7bd57
[   78.209264] PrId  : 0001992f (MIPS 1004Kc)
[   78.213333] Modules linked in: crypto_hw_eip93(+) pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 des_generic authenc leds_gpio gpio_button_hotplug [last unloaded: crypto_hw_eip93]
[   78.276089] Process insmod (pid: 1381, threadinfo=8f340000, task=8fe6ce00, tls=77fd8ee8)
[   78.284136] Stack : 00000000 808d0000 8e53b794 00000008 00000028 8f2feb80 80080d1c 8f2feb80
[   78.292469]         0000001b 802e8b88 1e004000 8f341b8c 00000000 802e0d28 8fdb0880 8f2feb80
[   78.300801]         8fdb0980 80080d84 8fdb0980 8f341bb8 8f2feb80 802e0fb4 00000000 802e74a4
[   78.309133]         8f2feb80 8fdbc800 8fdbc810 00000000 808d0000 8e53b794 00000008 8e538868
[   78.317464]         8fd97a20 8fd97720 0000001b 00000003 00002000 8fdb0980 8f2feb80 00000028
[   78.325796]         ...
[   78.328233] Call Trace:
[   78.330668] [<80132c1c>] __kmalloc_track_caller+0x184/0x294
[   78.336228] [<802e8b88>] devres_alloc_node+0x2c/0x70
[   78.341189] [<80080d84>] devm_request_threaded_irq+0x58/0xf4
[   78.346847] [<8e538868>] mtk_initialize+0x184/0x5cc [crypto_hw_eip93]
[   78.353279] Code: 00000000  8e020014  02621021 <8c470000> 41666000  30c60001  000000c0  8f85000c  8e020000
[   78.363005]
[   78.364693] ---[ end trace fb7dbb6020071670 ]---
[   78.370816] Kernel panic - not syncing: Fatal exception

**Comment by vschagen** [comment]
Development has continued since this. No longer an issue on Kernel 5.4
