### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ykzj** [vschagen/mtk-eip93#8]
according to the guide in previous issue, I cp git to kernel directory, and try to compile, but I hit such error:

  CC [M]  /home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.o
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:14:10: fatal error: crypto/internal/des.h: No such file or directory
 #include <crypto/internal/des.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:326: recipe for target '/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.o' failed
make[5]: *** [/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.o] Error 1
Makefile:1542: recipe for target '_module_/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93' failed
make[4]: *** [_module_/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93] Error 2
make[4]: Leaving directory '/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-4.14.180'
Makefile:51: recipe for target '/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/.built' failed
make[3]: *** [/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/.built] Error 2
make[3]: Leaving directory '/home/xudong_liu_go/openwrt/package/kernel/mtk-eip93'
time: package/kernel/mtk-eip93/compile#1.03#0.48#1.30
package/Makefile:111: recipe for target 'package/kernel/mtk-eip93/compile' failed
make[2]: *** [package/kernel/mtk-eip93/compile] Error 2
make[2]: Leaving directory '/home/xudong_liu_go/openwrt'
package/Makefile:107: recipe for target '/home/xudong_liu_go/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/xudong_liu_go/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xudong_liu_go/openwrt'
/home/xudong_liu_go/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

I changed eip93-cipher.c:14:10 path to 
 **#include <crypto/des.h>**
and then I hit another error

/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:738:9: error: implicit declaration of function 'verify_skcipher_des_key'; did you mean 'mtk_skcipher_setkey'? [-Werror=implicit-function-declaration]
   ret = verify_skcipher_des_key(ctfm, key);
         ^~~~~~~~~~~~~~~~~~~~~~~
         mtk_skcipher_setkey
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:745:9: error: implicit declaration of function 'verify_skcipher_des3_key'; did you mean 'mtk_skcipher_setkey'? [-Werror=implicit-function-declaration]
   ret = verify_skcipher_des3_key(ctfm, key);
         ^~~~~~~~~~~~~~~~~~~~~~~~
         mtk_skcipher_setkey
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:756:9: error: implicit declaration of function 'crypto_sync_skcipher_setkey'; did you mean 'crypto_skcipher_setkey'? [-Werror=implicit-function-declaration]
   ret = crypto_sync_skcipher_setkey(ctx->fallback, key, len);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         crypto_skcipher_setkey
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c: In function 'mtk_skcipher_crypt':
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:786:3: error: implicit declaration of function 'SYNC_SKCIPHER_REQUEST_ON_STACK'; did you mean 'SKCIPHER_REQUEST_ON_STACK'? [-Werror=implicit-function-declaration]
   SYNC_SKCIPHER_REQUEST_ON_STACK(subreq, ctx->fallback);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   SKCIPHER_REQUEST_ON_STACK
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:786:34: error: 'subreq' undeclared (first use in this function); did you mean 'req'?
   SYNC_SKCIPHER_REQUEST_ON_STACK(subreq, ctx->fallback);
                                  ^~~~~~
                                  req
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:786:34: note: each undeclared identifier is reported only once for each function it appears in
/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.c:787:3: error: implicit declaration of function 'skcipher_request_set_sync_tfm'; did you mean 'skcipher_request_set_tfm'? [-Werror=implicit-function-declaration]
   skcipher_request_set_sync_tfm(subreq, ctx->fallback);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   skcipher_request_set_tfm
cc1: some warnings being treated as errors
scripts/Makefile.build:326: recipe for target '/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.o' failed
make[5]: *** [/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/eip93-cipher.o] Error 1
Makefile:1542: recipe for target '_module_/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93' failed
make[4]: *** [_module_/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93] Error 2
make[4]: Leaving directory '/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-4.14.180'
Makefile:51: recipe for target '/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/.built' failed
make[3]: *** [/home/xudong_liu_go/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93/.built] Error 2
make[3]: Leaving directory '/home/xudong_liu_go/openwrt/package/kernel/mtk-eip93'
time: package/kernel/mtk-eip93/compile#1.18#0.51#1.48
package/Makefile:111: recipe for target 'package/kernel/mtk-eip93/compile' failed
make[2]: *** [package/kernel/mtk-eip93/compile] Error 2
make[2]: Leaving directory '/home/xudong_liu_go/openwrt'
package/Makefile:107: recipe for target '/home/xudong_liu_go/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/xudong_liu_go/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xudong_liu_go/openwrt'
/home/xudong_liu_go/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

openwrt version: 19.07.3
kernel version: 4.14.180

**Comment by Ykidia** [comment]
This driver for kernel 5.4 and not for 4.x or earlier. But if you want to try, I created small patch for kernel 4.19 to get ability to compile and to successfully run this driver on 4.19. I don't know is this patch suitable for 4.14, but you can simply try it...

[103-upgrade-skcipher-api.tar.gz](https://github.com/vschagen/mtk-eip93/files/4674131/103-upgrade-skcipher-api.tar.gz)

**Comment by rdslw** [comment]
Guys (@Ykidia and @ykzj ) -> did you manage to port MTK-EIP93 fully to 4.14 ?
4.14 is openwrt release kernel.

**Comment by ykzj** [comment]
no, i managed compiling on 5.x kernel, but see no significant performance improvement 

发自我的iPad

**Comment by rdslw** [comment]
I managed also to compile it on 5.4. I see noticable improvements (3x.. 4x), cryptsetup benchmark results below (without and with mtk-eip93)

```
root@BEFORE:~# cryptsetup benchmark
# Tests are approximate using memory only (no storage IO).
#     Algorithm |       Key |      Encryption |      Decryption
        aes-cbc        128b        11.3 MiB/s        11.6 MiB/s
    serpent-cbc        128b         9.2 MiB/s         9.5 MiB/s
    twofish-cbc        128b        12.3 MiB/s        12.6 MiB/s
        aes-cbc        256b         9.0 MiB/s         9.1 MiB/s
    serpent-cbc        256b         9.2 MiB/s         9.5 MiB/s
    twofish-cbc        256b        12.4 MiB/s        12.7 MiB/s
        aes-xts        256b        11.7 MiB/s        11.6 MiB/s
    serpent-xts        256b         8.1 MiB/s         9.5 MiB/s
    twofish-xts        256b        12.9 MiB/s        12.9 MiB/s
        aes-xts        512b         9.1 MiB/s         9.1 MiB/s
    serpent-xts        512b         9.6 MiB/s         9.2 MiB/s
    twofish-xts        512b        12.9 MiB/s        12.9 MiB/s

#AFTER #################################
#     Algorithm |       Key |      Encryption |      Decryption
        aes-cbc        128b        39.3 MiB/s        39.6 MiB/s
    serpent-cbc        128b         8.4 MiB/s         9.5 MiB/s
    twofish-cbc        128b        11.0 MiB/s        12.7 MiB/s
        aes-cbc        256b        32.3 MiB/s        32.3 MiB/s
    serpent-cbc        256b         9.4 MiB/s         9.5 MiB/s
    twofish-cbc        256b        12.4 MiB/s        12.7 MiB/s
        aes-xts        256b        20.4 MiB/s        26.6 MiB/s
    serpent-xts        256b         6.5 MiB/s         9.5 MiB/s
    twofish-xts        256b         8.6 MiB/s        12.7 MiB/s
        aes-xts        512b        23.3 MiB/s        23.2 MiB/s
    serpent-xts        512b         9.6 MiB/s         9.5 MiB/s
    twofish-xts        512b        12.8 MiB/s        12.7 MiB/s
```
