### ISSUE TITLE
Is there any way to accelerate AES-256-GCM?

### ISSUE THREAD

**Issue by coolmaxter** [vschagen/mtk-eip93#9]
It seems that the EIP-93 doesn't suppport AES chiper in Galois mode. Is there anyway we can combine the hardware aes chiper(AES-256-CTR) with CPU for GCM?

**Comment by plappermaul** [comment]
Shouldn't it be enough to load Linux kernel GCM module that loads above hardware optimized AES-CTR?

From linux.git/tree/crypto/gcm.c

```
static int crypto_gcm_create_common(struct crypto_template *tmpl,
				    struct rtattr **tb,
				    const char *ctr_name,
				    const char *ghash_name)
{
	struct crypto_attr_type *algt;
	struct aead_instance *inst;
	struct skcipher_alg *ctr;
	struct crypto_alg *ghash_alg;
	struct hash_alg_common *ghash;
	struct gcm_instance_ctx *ctx;
	int err;

  ...
	err = -EINVAL;
	if (strcmp(ghash->base.cra_name, "ghash") != 0 ||
	    ghash->digestsize != 16)
		goto err_drop_ghash;

	...
	/* The skcipher algorithm must be CTR mode, using 16-byte blocks. */
	err = -EINVAL;
	if (strncmp(ctr->base.cra_name, "ctr(", 4) != 0 ||
	    crypto_skcipher_alg_ivsize(ctr) != 16 ||
	    ctr->base.cra_blocksize != 1)
		goto out_put_ctr;

	err = -ENAMETOOLONG;
	if (snprintf(inst->alg.base.cra_name, CRYPTO_MAX_ALG_NAME,
		     "gcm(%s", ctr->base.cra_name + 4) >= CRYPTO_MAX_ALG_NAME)
		goto out_put_ctr;

	if (snprintf(inst->alg.base.cra_driver_name, CRYPTO_MAX_ALG_NAME,
		     "gcm_base(%s,%s)", ctr->base.cra_driver_name,
		     ghash_alg->cra_driver_name) >=
	    CRYPTO_MAX_ALG_NAME)
		goto out_put_ctr;
		
   /* build new combined algorithm */
   ...
```

**Comment by coolmaxter** [comment]
It's strange, I use openssl speed and get different results.
```
OpenSSL 1.1.1g  21 Apr 2020
built on: Wed Jun  3 09:34:28 2020 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr)
compiler: mipsel-openwrt-linux-musl-gcc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
```

> openssl speed -elapsed -evp aes-256-ctr

```
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-ctr        600.13k     1261.10k     5867.43k    17057.79k    39253.56k    42456.41k
root@OpenWrt:~# openssl speed -elapsed -evp aes-256-gcm
```

> openssl speed -elapsed -evp aes-256-ctr

```
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-gcm       4656.80k     5087.64k     5228.71k     5242.47k     5251.07k     5264.73k

```

**Comment by plappermaul** [comment]
Have a Look at /proc/crypto. It should read something like gcm(aes-ctr-eip-hwcrypto). If yes the kernel should provide accelleration. But do Not know what must happen that openssl takes the cipher.

Am 18.06.2020 12:53 schrieb coolmaxter <notifications@github.com>:

It's strange, I use openssl speed and get different results.

OpenSSL 1.1.1g  21 Apr 2020
built on: Wed Jun  3 09:34:28 2020 UTC
options:bn(64,32) rc4(char) des(long) aes(partial) blowfish(ptr)
compiler: mipsel-openwrt-linux-musl-gcc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT


openssl speed -elapsed -evp aes-256-ctr

The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-ctr        600.13k     1261.10k     5867.43k    17057.79k    39253.56k    42456.41k
root@OpenWrt:~# openssl speed -elapsed -evp aes-256-gcm


openssl speed -elapsed -evp aes-256-ctr

The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256-gcm       4656.80k     5087.64k     5228.71k     5242.47k     5251.07k     5264.73k

**Comment by hilihan** [comment]
Hi, I meet same problem here. i checked my crypto list, where no gcm crypto related with gcm throught eip-93
`root@OpenWrt:/proc# cat /proc/crypto | grep eip
driver       : eip93-authenc-hmac-sha256-ecb-cipher-null
module       : crypto_hw_eip93
driver       : eip93-authenc-hmac-sha224-ecb-cipher-null
module       : crypto_hw_eip93
driver       : eip93-authenc-hmac-sha1-ecb-cipher-null
module       : crypto_hw_eip93
driver       : eip93-authenc-hmac-md5-ecb-cipher-null
module       : crypto_hw_eip93
driver       : authenc(hmac(sha256-eip93),rfc3686(ctr(aes-eip93)))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha224-eip93),rfc3686(ctr(aes-eip93)))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha1-eip93),rfc3686(ctr(aes-eip93)))
module       : crypto_hw_eip93
driver       : authenc(hmac(md5-eip93),rfc3686(ctr(aes-eip93)))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha256-eip93),cbc(aes-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha224-eip93),cbc(aes-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha1-eip93),cbc(aes-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(md5-eip93), cbc(aes-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha256-eip93),cbc(des3_ede-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha224-eip93),cbc(des3_ede-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha1-eip93),cbc(des3_ede-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(md5-eip93),cbc(des3_ede-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha256-eip93),cbc(des-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha224-eip93),cbc(des-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(sha1-eip93),cbc(des-eip93))
module       : crypto_hw_eip93
driver       : authenc(hmac(md5-eip93),cbc(des-eip93))
module       : crypto_hw_eip93
driver       : rfc3686(ctr(aes-eip93))
module       : crypto_hw_eip93
driver       : ctr(aes-eip93)
module       : crypto_hw_eip93
driver       : cbc(aes-eip93)
module       : crypto_hw_eip93
driver       : ecb(aes-eip93)
module       : crypto_hw_eip93
driver       : cbc(des3_ede-eip93)
module       : crypto_hw_eip93
driver       : ecb(des3_ede-eip93)
module       : crypto_hw_eip93
driver       : cbc(des-eip93)
module       : crypto_hw_eip93
driver       : ebc(des-eip93)
module       : crypto_hw_eip93
root@OpenWrt:/proc# cat /proc/crypto | grep gcm

**Comment by plappermaul** [comment]
Did you compile kernel with module gcm? if yes and gcm is not loaded how about loading it?

`modprobe gcm`

**Comment by coolmaxter** [comment]
> Did you compile kernel with module gcm? if yes and gcm is not loaded how about loading it?
> 
> `modprobe gcm`
I have loaded this module but nothing changes.
In the crypto driver compile, this module is reqired by the eip-93 driver.

**Comment by vschagen** [comment]
The short answer is: it should work with hardware offload for aes-ctr and do software hash.

Longer answer: It doesn't at the moment. Like other crypto drivers I am also having issues getting this to work with the standard linux version. (Seems a DMA and cache problem).

**Comment by vschagen** [comment]
I will push an aes-ctr work-around to get it to work with gcm. This will also reduce normal aes-ctr performance, but will not affect rfc3686(ctr(aes)). The last one is actually the counter mode that the engine was designed for. (32 bit counter vs 64 as in the kernel). On big blocks it can out perform software, but I doubt for smaller blocks it is useful. I will revisit this problem later.

Simple "insmod tcrypt mode=211" test to demonstrate it works:

[  154.658371] testing speed of rfc4106(gcm(aes)) (rfc4106(gcm_base(ctr(aes-eip93),ghash-generic))) encryption
[  154.669718] test 0 (160 bit key, 16 byte blocks): 
[  154.670404] 1 operation in 22045 cycles (16 bytes)
[  154.680093] test 1 (160 bit key, 64 byte blocks): 
[  154.680771] 1 operation in 23456 cycles (64 bytes)
[  154.690437] test 2 (160 bit key, 256 byte blocks): 
[  154.691287] 1 operation in 30123 cycles (256 bytes)
[  154.701181] test 3 (160 bit key, 512 byte blocks): 
[  154.702300] 1 operation in 39365 cycles (512 bytes)
[  154.712149] test 4 (160 bit key, 1024 byte blocks): 
[  154.713733] 1 operation in 56878 cycles (1024 bytes)
[  154.723761] test 5 (160 bit key, 2048 byte blocks): 
[  154.726363] 1 operation in 94353 cycles (2048 bytes)
[  154.736383] test 6 (160 bit key, 4096 byte blocks): 
[  154.741005] 1 operation in 168757 cycles (4096 bytes)
[  154.751070] test 7 (160 bit key, 8192 byte blocks): 
[  154.759798] 1 operation in 317257 cycles (8192 bytes)

[  301.651570] testing speed of rfc4106(gcm(aes)) (rfc4106(gcm_base(ctr(aes-generic),ghash-generic))) encryption
[  301.663082] test 0 (160 bit key, 16 byte blocks): 
[  301.663290] 1 operation in 5267 cycles (16 bytes)
[  301.672864] test 1 (160 bit key, 64 byte blocks): 
[  301.673109] 1 operation in 8170 cycles (64 bytes)
[  301.682653] test 2 (160 bit key, 256 byte blocks): 
[  301.683218] 1 operation in 19886 cycles (256 bytes)
[  301.693031] test 3 (160 bit key, 512 byte blocks): 
[  301.694026] 1 operation in 35509 cycles (512 bytes)
[  301.703829] test 4 (160 bit key, 1024 byte blocks): 
[  301.705671] 1 operation in 66688 cycles (1024 bytes)
[  301.715640] test 5 (160 bit key, 2048 byte blocks): 
[  301.719261] 1 operation in 129231 cycles (2048 bytes)
[  301.729299] test 6 (160 bit key, 4096 byte blocks): 
[  301.736434] 1 operation in 263750 cycles (4096 bytes)
[  301.746466] test 7 (160 bit key, 8192 byte blocks): 
[  301.760480] 1 operation in 508927 cycles (8192 bytes)

**Comment by coolmaxter** [comment]
Thanks. most SSL has implemented gcm encryption, this will help the acceleration.

**Comment by vschagen** [comment]
Follow up:

With Strongswan and an ESP = aes128gcm96-aes128gmac I see around 45/45 mbps vs 30/33 with only software running iperf3 between a PC on the WAN side which established an esp tunnel with an MT7621 router and a PC on the LAN side of that router.

So with full NAT and routing on ipv4.
